### ISSUE TITLE
How to install smartcheck?

### ISSUE THREAD

**Issue by xf97** [smartdec/smartcheck#18]
Hello, I am a student who wants to use smartcheck. I made a mistake when installing SmartCheck using npm install @smartdec / smartcheck -g. The system environment is win10. Could I install SmartCheck in this way now?

**Comment by eMarchenko** [comment]
hi!
I've just checked checked installation process (on win10)
* install: `npm install @smartdec/smartcheck -g`
* run: `smartcheck -p <dir or file>`
