### ISSUE TITLE
Test not passing: IllegalStateException

### ISSUE THREAD

**Issue by yxliang01** [smartdec/smartcheck#20]
When I build via `mvn clean package` with Maven 3.6, OpenJDK 8, I received a test error: 
```
IllegalStateException: SOLIDITY_FUNCTIONS_RETURNS_TYPE_AND_NO_RETURN
```

from

https://github.com/smartdec/smartcheck/blob/774e8b326e6384a21a5beaa707c9929079f88f07/src/test/java/ru/smartdec/smartcheck/RulesTest.java#L217

Also see the screenshot for stacktrace:
![image](https://user-images.githubusercontent.com/9780746/57183651-9bf99480-6ee2-11e9-91fe-be15ecfac442.png)

Currently, this prevents SmartCheck being built.

Thanks

**Comment by eMarchenko** [comment]
Hi! I've updated tests, please check again.
