### ISSUE TITLE
Number of problem types that smartCheck can detect today

### ISSUE THREAD

**Issue by xf97** [smartdec/smartcheck#23]
Hello, I am a postgraduate student from Hehai University. Compared with the 21 smart contract issues you mentioned in your paper, smartCheck has now been able to detect a significant increase in the types of problems. I would like to ask how many smart contract issues SmartCheck covers today, and what are the criteria for determining each one? We look forward to your reply.

**Comment by eMarchenko** [comment]
Hi!
Yes, we've added bunch of rules. 
You could check them 
* either in the [rule files](https://github.com/smartdec/smartcheck/tree/master/src/main/resources) - there are comments briefly describing what does particular pattern look for
* or in the [description folders](https://github.com/smartdec/smartcheck/tree/master/rule_descriptions), which contain more additional information

And we are going to update rules soon, there are significant improvements.

**Comment by xf97** [comment]
Thank you for your reply, which has helped me a lot. Best wishes to you.


At 2019-09-11 17:33:56, "Evgeny" <notifications@github.com> wrote:


Hi!
Yes, we've added bunch of rules.
You could check them

either in the rule files - there are comments briefly describing what does particular pattern look for
or in the description folders, which contain more additional information

And we are going to update rules soon, there are significant improvements.

**Comment by xf97** [comment]
Thank you for your reply, which has helped me, and I wish you a happy life!

At 2019-09-11 17:33:56, "Evgeny" <notifications@github.com> wrote:


Hi!
Yes, we've added bunch of rules.
You could check them

either in the rule files - there are comments briefly describing what does particular pattern look for
or in the description folders, which contain more additional information

And we are going to update rules soon, there are significant improvements.
