### ISSUE TITLE
Does SmartCheck analyse multiple contracts in a file?

### ISSUE THREAD

**Issue by lukwue** [smartdec/smartcheck#33]
Does SmartCheck analyse multiple contracts in a file? Can I specify which contracts it should analyse?

Thank you!

**Comment by eMarchenko** [comment]
It analyzes all lines in a file. You cannot specify particular contract.
Unless you are working with a flatten file you should have contracts in separate files, in this case you can choose which ones to pass to SmartCheck.

**Comment by lukwue** [comment]
Thank you!
