### ISSUE TITLE
Which of the rules in the rule description cover a reentrancy vulnerability?

### ISSUE THREAD

**Issue by lukwue** [smartdec/smartcheck#34]
Hello,

in your paper, you mention that your tool looks for reentrancy vulnerabilities. However, I could not find it in the [rule description](https://github.com/smartdec/smartcheck/tree/master/rule_descriptions) directory.  

Does your current tool still look for the issue? And if, which rule does check for it?

Thanks!

Lukas

**Comment by eMarchenko** [comment]
Hi Lukas

We have removed reentrancy rule, as it was producing way to many false positives. 
There are other tools that look for it much better, or at least correctly identify `Checks-Effects-Interactions` pattern violations.

Evgeny

**Comment by lukwue** [comment]
Hi Evgeny,

Thank you!

That's what I already thought.
