### ISSUE TITLE
hi ！Can this result be converted to JSON format？

### ISSUE THREAD

**Issue by TheKingShun** [smartdec/smartcheck#37]
Is there a built-in command to output JSON
i get the results like:

ruleId: SOLIDITY_VISIBILITY
patternId: 910067
severity: 1
line: 43
column: 4
content: functionVictim()payable{}

ruleId: SOLIDITY_VISIBILITY
patternId: 910067
severity: 1
line: 44
column: 4
content: functionwithDraw(){uintamount=userBalannce[msg.sender];if(amount>0){msg.sender.call.value(amount)();userBalannce[msg.sender]=0;}}

ruleId: SOLIDITY_VISIBILITY
patternId: 910067
severity: 1
line: 51
column: 4
content: functionreceiveEther()payable{if(msg.value>0){userBalannce[msg.sender]+=msg.value;}}

SOLIDITY_VISIBILITY :6
SOLIDITY_PRAGMAS_VERSION :1
SOLIDITY_UPGRADE_TO_050 :1
SOLIDITY_CALL_WITHOUT_DATA :1
SOLIDITY_EXACT_TIME :1

**Comment by eMarchenko** [comment]
Hi! SmartCheck doesn't support standard output formats. And it is effectively discontinued as for now.
If you are good with java you could implement this feature - the codebase is small and you don't need to mess up with the search engine.

**Comment by TheKingShun** [comment]
@eMarchenko 

Thank you very much

**Comment by gfaura** [comment]
> Hi! SmartCheck doesn't support standard output formats. And it is effectively discontinued as for now.
> If you are good with java you could implement this feature - the codebase is small and you don't need to mess up with the search engine.

Hi, so Smartcheck is now discontinued and will not be maintained anymore? Is this confirmed? What other static analyser for Solidity would you recommend using instead?

**Comment by eMarchenko** [comment]
SmartCheck's future is uncertain. 
[Slither](https://github.com/crytic/slither) is a powerful open-source analyzer. If you have time to run only one security tool, this one might be the best choice.

**Comment by gfaura** [comment]
OK, thanks for the speedy reply! I'll give it a go.
Any recommended set-up to run it on a Windows OS?

**Comment by eMarchenko** [comment]
Slither doesn't work on windows =\
You can use github actions or similar CI solution to run it on push, it's a preferred solution anyway

**Comment by gfaura** [comment]
great, thanks!
