### ISSUE TITLE
https://tool.smartdec.net not working anymore

### ISSUE THREAD

**Issue by ShivamDev31** [smartdec/smartcheck#38]
Hi Team the website is not working anymore. Can you please look into this. Thanks

**Comment by eMarchenko** [comment]
Hi! unfortunately, web site is discontinued
You can run SmartCheck locally:
- use npm [package](https://www.npmjs.com/package/@smartdec/smartcheck)
- build with maven from sources

**Comment by ShivamDev31** [comment]
Thanks for the reply @eMarchenko
