### ISSUE TITLE
ruleId Information

### ISSUE THREAD

**Issue by omarandres2803** [smartdec/smartcheck#42]
Hello,
I'm using the tool to detect some vulnerabilities in a simple solidity smart contract. The output says there is a vulnerability in the code, with a ruleId related to it. 

Where can I find more information regarding these ruleIds?

Thanks

**Comment by eMarchenko** [comment]
Hi
There are descriptions, examples, recommendations, and useful links for all (most?) ruleId it the [`rule_descriptions/`](https://github.com/smartdec/smartcheck/tree/master/rule_descriptions) folder
