### ISSUE TITLE
output

### ISSUE THREAD

**Issue by taylorgag** [smartdec/smartcheck#43]
Sorry to bother you, how do I print the results to a specific file instead of displaying them on the terminal? what command?

**Comment by eMarchenko** [comment]
Hi! SmartCheck doesn't include such feature. You can achieve similar results via terminal redirecting options, i.e., `smartcheck -p . > output.txt`

**Comment by 161424** [comment]
Can you tell me how you run successfully? My has been reporting mistakes. For the time being, it's all the mistakes reported by nodejs, even though I've changed the old version

**Comment by 161424** [comment]
> Can you tell me how you run successfully? My has been reporting mistakes. For the time being, it's all the mistakes reported by nodejs, even though I've changed the old version I changed different versions of nodejs. Except for different error codes, the rest are the same as follows PS C:\Users\11251> node --trace-warnings ... internal/modules/cjs/loader.js:905 throw err; ^
> 
> Error: Cannot find module 'C:\Users\11251...' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15) at Function.Module._load (internal/modules/cjs/loader.js:746:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }



> Can you tell me how you run successfully? My has been reporting mistakes. For the time being, it's all the mistakes reported by nodejs, even though I've changed the old version I changed different versions of nodejs. Except for different error codes, the rest are the same as follows PS C:\Users\11251> node --trace-warnings ... internal/modules/cjs/loader.js:905 throw err; ^
> 
> Error: Cannot find module 'C:\Users\11251...' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15) at Function.Module._load (internal/modules/cjs/loader.js:746:27) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) at internal/main/run_main_module.js:17:47 { code: 'MODULE_NOT_FOUND', requireStack: [] }

It baffled me. After changing a path, it runs successfully. Is it because the previous path is too long or because there is Chinese???? And its absurdity

**Comment by eMarchenko** [comment]
I'm sorry to hear it. SmatCheck is discontinued and provided "as is", with all its features and bugs.
Anyway, I'm glad that you've figured it out and launched the tool.
