### ISSUE TITLE
Clarification on Reentrancy Detection Capabilities in SmartCheck

### ISSUE THREAD

**Issue by MarkLee131** [smartdec/smartcheck#46]
Hi, thanks for you guys providing this tool for smart contract security. 
I noticed that your team has mentioned the removal of reentrancy detection from the rules in several issues including [#34](https://github.com/smartdec/smartcheck/issues/34). 
However, I noticed that another rule, `SOLIDITY_CALL_WITHOUT_DATA`, is mapped to reentrancy issues by SmartBugs at https://github.com/smartbugs/smartbugs/wiki/Vulnerabilities-mapping. 
This has led to some confusion on my part regarding the current capabilities of SmartCheck concerning reentrancy detection.

Could you please clarify whether the `SOLIDITY_CALL_WITHOUT_DATA` rule is intended to serve as a mechanism for detecting reentrancy vulnerabilities, or if it addresses a different concern? 
Given the critical nature of reentrancy in smart contract security, understanding SmartCheck's current capabilities and limitations in this area is essential for users.

Thank you in advance for your insights and clarification. :)

**Comment by MarkLee131** [comment]
Hi @eMarchenko , can you kindly give some insights? :)

**Comment by eMarchenko** [comment]
Hi @MarkLee131 , thank you for the interest to SmartCheck.
Just as a disclaimer, SmartCheck is discontinued for quite a while and may produce garbish results for Solidity 0.6 and later.
Nonetheless, `SOLIDITY_CALL_WITHOUT_DATA` might still work correctly.

To clarify logic of any rule you can check [rules.xml file](https://github.com/smartdec/smartcheck/blob/master/src/main/resources/solidity-rules.xml#L167-L169).
`SOLIDITY_CALL_WITHOUT_DATA` looks for `<address>.call("")` patterns in the code. These unlimited calls may result in re-entrancy, though it's a weak predictor. E.g., the contract may follow CEI pattern or include `nonreentrant` protection.
Overall, I'd assume that Slither produces much better results regarding re-entrancy detection (less FP/FN).

Regarding the `SOLIDITY_CALL_WITHOUT_DATA` usefulness for other problems:
- under some circumstances, an attacker can use it to cause DoS/griefing.

I hope this information is helpful.

**Comment by MarkLee131** [comment]
Thanks for the clarification @eMarchenko . It is very helpful and provides many insights on SAST in Solidity smart contracts, especially on SmartCheck. Have a nice day!
