### ISSUE TITLE
and there is the error again

### ISSUE THREAD

**Issue by IamChuancey** [smartdec/smartcheck#8]
https://github.com/smartdec/smartcheck
![image](https://user-images.githubusercontent.com/29730996/51580929-2bb19f00-1f01-11e9-949e-703f85f51a56.png)

**Comment by eMarchenko** [comment]
well it corresponds to this code:
```
        Path src = arguments
                .value("-p", "--path")
                .map(Paths::get)
                .filter(Files::exists)
                .orElseThrow(IllegalArgumentException::new);
```
You've probably missed command line arguments (`-p` in this case) or the path provided doesn't exist or whatever.
