### ISSUE TITLE
a user interface is needed,haha

### ISSUE THREAD

**Issue by IamChuancey** [smartdec/smartcheck#9]
![image](https://user-images.githubusercontent.com/29730996/51611990-82e45d80-1f5b-11e9-9ebb-99fdba1c23b6.png)
It seems that it finally works, but what disappoints me a little is there is no user interface, looking  forward to your good job! And what you have done is really great!

**Comment by eMarchenko** [comment]
Please use this [web-interface](https://tool.smartdec.net/). It runs this analysis engine under the hood.
